### ISSUE TITLE
YouTube embeded video autoplay- Hacktoberfest

### ISSUE THREAD

**Issue by maddhruv** [maddhruv/maddhruv.github.io#2]
Make the embeded video autoplay as the search is clicked.
Hacktoberfest

**Comment by efl7a** [comment]
Can I try this one?

**Comment by maddhruv** [comment]
Hey! Thanks for reaching out but,
This doesn't exist anymore!

**Comment by efl7a** [comment]
And that is what I was discovering going through your code.  No worries!
